# version: 2.1

# jobs:
#   Test:
#     docker:
#       - image: circleci/python:3.7.3
#     steps:
#       - checkout
#       - run: make install
#       - run: make install-linters
#       - run: make lint
  
  
# # Orchestrate our job run sequence
# workflows:
#   Test:
#     jobs:
#       - Test




version: 2.1 
jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: circleci/python:3.7.3

      working_directory: ~/repo

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
        
      - run:
      name: install dependencies
      command: |
        python3 -m venv venv
        . venv/bin/activate
        make install
      - run:
        name: install dependencies
        command: |
          make install-linters
        - save_cache:
            paths:
              - ./venv
              key: v1-dependencies-{{ checksum "requirements.txt" }}
        
        # run lint!
      - run:
        name: run lint
        command: |
          . venv/bin/activate
          make lint 
      

workflows:
  Build:
    jobs:
      - Build